spring:
  application:
    name: apiTienda
  profiles:
    active: local
---
spring:
  profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/truck-health
    username: postgres
    password: 1041971977
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
